//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public int Atten_ID { get; set; }
        public int Stud_ID { get; set; }
        public bool Present { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
